export const materials = [
  {
    id: 1,
    nombre: "Ceibalita",
    src: "https://www.lr21.com.uy/wp-content/uploads/2020/03/plan-ceibal.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur . Duis aute irure dolor in reprehenderit",
    state: "Buen",
    category: "Laptops",
  },
  {
    id: 2,
    nombre: "Auricular",
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Earphones_BW_2011-12-10_15-49-08.JPG/1200px-Earphones_BW_2011-12-10_15-49-08.JPG",
    desc: "Lorem ipsum dolor sit amet, consectetur . Duis aute irure dolor in reprehenderit",
    state: "Mal",
    category: "Auriculares",
  },
  {
    id: 3,
    nombre: "Cargador",
    src: "https://www.digitaloutlet.com.uy/imgs/productos/productos34_3721.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur . Duis aute irure dolor in reprehenderit",
    state: "Regular",
    category: "Cargadores",
  },
  {
    id: 4,
    nombre: "GOD ceibalita",
    src: "https://icdn.dtcn.com/image/digitaltrends_es/185-xps-13-laptop-resized-2.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur . Duis aute irure dolor in reprehenderit",
    category: "Laptops",
  },
  {
    id: 5,
    nombre: "Martillo",
    src: "https://geant.vteximg.com.br/arquivos/ids/268992-1000-1000/478372.jpg?v=637522818658200000",
    desc: "Lorem ipsum dolor sit amet, consectetur . Duis aute irure dolor in reprehenderit",
    state: "Buen",
    category: "Herramientas",
  },
  {
    id: 6,
    nombre: "Ceibalita",
    src: "https://www.lr21.com.uy/wp-content/uploads/2020/03/plan-ceibal.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur . Duis aute irure dolor in reprehenderit",
    state: "Buen",
    category: "Laptops",
  },
];
